apiVersion : apps/v1
kind: Deployment
metadata:
  name: web-deploy-multi-pod
  labels:
    app : web-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      project: test2
  template:
    metadata:
      labels:
        project: test2
    spec:
      containers:
        - name: test-web
          image: borisovnn/k8stest:latest
          ports:
            - containerPort: 80

        - name: test2-web
          image: tomcat:8.5.38
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: multi-pods-service
  labels:
    env: prod
    owner: borisovnn
spec:
  type: LoadBalancer
  selector:
    project: test2
  ports:
    - name: web-app-listener
      protocol: TCP
      port: 80
      targetPort: 80

    - name: second-web-app-listener
      protocol: TCP
      port: 8888
      targetPort: 8080