apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy-autoscaling
  labels:
    app: k8s-deploy
spec:
  selector:
    matchLabels:
      project: test3
  template:
    metadata:
      labels:
        project: test3
    spec:
      containers:
        - name: test3-web
          image: borisovnn/k8stest:latest
          ports:
            - containerPort: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: test-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-deploy-autoscaling
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: autoscaling-pod-service
  labels:
    env: prod
    owner: borisovnn
spec:
  selector:
    app: test3
  ports:
  - name: app-listener
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
