apiVersion : apps/v1
kind: Deployment
metadata:
  name: web-deploy
  labels:
    app : web-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      project: test
  template:
    metadata:
      labels:
        project: test
    spec:
      containers:
        - name: test-web
          image: borisovnn/k8stest:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: single-pod-service
  labels:
    env   : prod
    owner : borisovnn
spec:
  selector:
    project: test # Selecting pods with those Labels
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 80 # Port on LoadBalancer
      targetPort: 80 # Port on POD
  type: LoadBalancer